Add tests for product module
rubygarage/shopapp-android pull request #139
Opened 2018-02-27 13:57 UTC by DenysZP

2018-02-27 14:41 UTC, starikovskii approved these changes

2018-03-01 10:47 UTC, plzen requested changes

2018-03-01 10:47 UTC, plzen commented on app/src/test/java/com/shopapp/ui/product/contract/ProductDetailsPresenterTest.kt
> +@RunWith(RobolectricTestRunner::class)
Remove robolectric from this test

2018-03-01 10:47 UTC, plzen commented on app/src/test/java/com/shopapp/ui/product/contract/ProductListPresenterTest.kt
> +@RunWith(RobolectricTestRunner::class)
Remove robolectric from this test

2018-03-01 11:44 UTC, plzen approved these changes

2018-03-01 11:49 UTC, merged